import java.nio.channels.AlreadyBoundException;

public class Arithmetic {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		int[] arr= {1,2,3};
		try {
			System.out.println(7 / 1);
			try {
				System.out.println(5 / arr[5]);
			}
			catch (NullPointerException exp2) {
				System.out.println("NullPointer Exception "+ exp2);
			    }
		} 
		catch (ArithmeticException exception) {
			System.out.println("Arithmetic Exception " + exception);
		}
		catch (NullPointerException exp) {
		System.out.println("NullPointer Exception "+ exp);
	    }
//		catch (ArrayIndexOutOfBoundsException expt) {
//		System.out.println("ArrayIndexOutOfBoundsException "+ expt);
//	    }
		catch(Exception e) {
			System.out.println("Generic Exception");
		}
		finally { 
			  System.out.println("Result"); 
			  }
		 
	}

}
